// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {plugin} from '../models';
import {prompt} from '../models';
import {main} from '../models';
import {data} from '../models';

export function AIAnalyzeByTypeStream(arg1:string,arg2:string,arg3:string):Promise<void>;

export function AIAnalyzeStock(arg1:string):Promise<models.AIChatResponse>;

export function AIAnalyzeStockStream(arg1:string):Promise<void>;

export function AIChat(arg1:models.AIChatRequest):Promise<models.AIChatResponse>;

export function AIChatStream(arg1:models.AIChatRequest):Promise<void>;

export function AIChatStreamWithPlugin(arg1:string,arg2:string):Promise<void>;

export function AIChatWithPlugin(arg1:string,arg2:Array<plugin.AIChatMessage>):Promise<string>;

export function AIRecommend():Promise<models.AIChatResponse>;

export function AIRecommendStream():Promise<void>;

export function AISummarizeContentStream(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:string):Promise<void>;

export function AddFund(arg1:string):Promise<void>;

export function AddFutures(arg1:string,arg2:string,arg3:string):Promise<void>;

export function AddHKStock(arg1:string,arg2:string,arg3:string):Promise<void>;

export function AddPlugin(arg1:Record<string, any>):Promise<void>;

export function AddPosition(arg1:models.Position):Promise<void>;

export function AddStock(arg1:string):Promise<void>;

export function AddStockAlert(arg1:models.StockAlert):Promise<void>;

export function AddUSStock(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function CheckStockAlerts():Promise<Array<models.AlertNotification>>;

export function CheckUpdate():Promise<models.UpdateInfo>;

export function CleanupAllCache():Promise<Record<string, number>>;

export function CleanupFinancialCache():Promise<number>;

export function CleanupNewsCache():Promise<number>;

export function CleanupQuoteCache():Promise<number>;

export function CleanupReportCache():Promise<number>;

export function ClearCache():Promise<void>;

export function ClearOldAIData():Promise<number>;

export function CreateAIPluginFromTemplate(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<void>;

export function CreatePluginFromTemplate(arg1:string,arg2:string,arg3:Record<string, string>):Promise<void>;

export function CreatePrompt(arg1:string,arg2:string,arg3:string):Promise<prompt.PromptInfo>;

export function DeleteAIAnalysisResult(arg1:number):Promise<void>;

export function DeleteAIChatSession(arg1:string):Promise<void>;

export function DeletePlugin(arg1:string):Promise<void>;

export function DeletePosition(arg1:number):Promise<void>;

export function DeletePrompt(arg1:string,arg2:string):Promise<void>;

export function DeleteStockAlert(arg1:number):Promise<void>;

export function DownloadAndInstallUpdate():Promise<models.UpdateInfo>;

export function ExecuteIndicatorPrompt(arg1:string,arg2:string):Promise<prompt.IndicatorResult>;

export function ExecuteReviewPrompt(arg1:string):Promise<prompt.ReviewResult>;

export function ExecuteScreenerPrompt(arg1:string):Promise<prompt.ScreenerResult>;

export function ExportAIAnalysisHistory(arg1:string):Promise<string>;

export function ExportAIChatHistory(arg1:string,arg2:string):Promise<string>;

export function ExportPlugin(arg1:string):Promise<string>;

export function ExportPrompt(arg1:string,arg2:string):Promise<string>;

export function FetchQuoteFromAllPlugins(arg1:string):Promise<plugin.DatasourceResult>;

export function FetchQuoteFromPlugin(arg1:string,arg2:string):Promise<plugin.DatasourceResult>;

export function GetAIAnalysisHistory():Promise<Array<models.AIAnalysisResult>>;

export function GetAIChatHistory():Promise<Array<main.AIChatSession>>;

export function GetAIDataCleanupInfo():Promise<Record<string, any>>;

export function GetAITemplates():Promise<Array<any>>;

export function GetAShareSentiment():Promise<data.MarketSentiment>;

export function GetActivePersona():Promise<string>;

export function GetAllAlerts():Promise<Array<models.StockAlert>>;

export function GetCachedGlobalMarketData(arg1:string):Promise<main.CachedGlobalMarketData>;

export function GetCachedMarketData():Promise<main.CachedMarketData>;

export function GetConfig():Promise<models.Config>;

export function GetDataCleanupInfo():Promise<main.DataCleanupInfo>;

export function GetDataPipelineStatus():Promise<models.DataPipelineStatus>;

export function GetDatasourceTemplates():Promise<Array<any>>;

export function GetEnabledAIPlugins():Promise<Array<plugin.Plugin>>;

export function GetEnabledDatasourcePlugins():Promise<Array<plugin.Plugin>>;

export function GetForexRates():Promise<Array<models.ForexRate>>;

export function GetFundList():Promise<Array<models.Fund>>;

export function GetFundPrice(arg1:Array<string>):Promise<Record<string, models.FundPrice>>;

export function GetFuturesList():Promise<Array<models.Futures>>;

export function GetFuturesPrice(arg1:Array<string>):Promise<Record<string, models.FuturesPrice>>;

export function GetFuturesProducts():Promise<Array<models.FuturesProduct>>;

export function GetGlobalIndices():Promise<Array<models.GlobalIndex>>;

export function GetGlobalIndicesList():Promise<Array<models.GlobalIndex>>;

export function GetGlobalMarketSentiment(arg1:string):Promise<data.MarketSentiment>;

export function GetGlobalNews(arg1:string):Promise<Array<models.NewsItem>>;

export function GetHKStockList():Promise<Array<models.HKStock>>;

export function GetHKStockPrice(arg1:Array<string>):Promise<Record<string, models.HKStockPrice>>;

export function GetHotTopics():Promise<Array<models.HotTopic>>;

export function GetIndustryRank():Promise<Array<models.IndustryRank>>;

export function GetKLineData(arg1:string,arg2:string,arg3:number):Promise<Array<models.KLineData>>;

export function GetLongTigerRank():Promise<Array<models.LongTigerItem>>;

export function GetMainContracts():Promise<Array<models.FuturesPrice>>;

export function GetMainForexPairs():Promise<Array<models.ForexRate>>;

export function GetMarketIndex():Promise<Array<models.MarketIndex>>;

export function GetMinuteData(arg1:string):Promise<Array<models.MinuteData>>;

export function GetMoneyFlow():Promise<Array<models.MoneyFlow>>;

export function GetNewsList():Promise<Array<models.NewsItem>>;

export function GetNotificationTemplates():Promise<Array<plugin.NotificationTemplate>>;

export function GetPlugin(arg1:string):Promise<plugin.Plugin>;

export function GetPlugins():Promise<Array<plugin.Plugin>>;

export function GetPluginsByType(arg1:string):Promise<Array<plugin.Plugin>>;

export function GetPluginsDir():Promise<string>;

export function GetPopularHKStocks():Promise<Array<models.HKStock>>;

export function GetPopularUSStocks():Promise<Array<models.USStock>>;

export function GetPositionByStock(arg1:string):Promise<models.Position>;

export function GetPositionHistory():Promise<Array<models.Position>>;

export function GetPositions():Promise<Array<models.Position>>;

export function GetPrompt(arg1:string,arg2:string):Promise<prompt.PromptInfo>;

export function GetPromptTypes():Promise<Array<any>>;

export function GetPromptsDir():Promise<string>;

export function GetResearchReports(arg1:string):Promise<Array<models.ResearchReport>>;

export function GetStockAlerts(arg1:string):Promise<Array<models.StockAlert>>;

export function GetStockList():Promise<Array<models.Stock>>;

export function GetStockNotices(arg1:string):Promise<Array<models.StockNotice>>;

export function GetStockPrice(arg1:Array<string>):Promise<Record<string, models.StockPrice>>;

export function GetTradingTimeInfo():Promise<main.TradingTimeInfo>;

export function GetUSStockList():Promise<Array<models.USStock>>;

export function GetUSStockPrice(arg1:Array<string>):Promise<Record<string, models.USStockPrice>>;

export function GetVersion():Promise<models.VersionInfo>;

export function HasEnabledAIPlugins():Promise<boolean>;

export function HasEnabledDatasourcePlugins():Promise<boolean>;

export function HasEnabledNotificationPlugins():Promise<boolean>;

export function ImportPlugin(arg1:string):Promise<plugin.Plugin>;

export function ImportPrompt(arg1:string,arg2:string,arg3:string):Promise<prompt.PromptInfo>;

export function IsFirstLoad():Promise<boolean>;

export function ListAllPrompts():Promise<Record<string, Array<prompt.PromptInfo>>>;

export function ListPrompts(arg1:string):Promise<Array<prompt.PromptInfo>>;

export function MarkFirstLoadComplete():Promise<void>;

export function OpenPluginsDir():Promise<void>;

export function OpenPromptsDir():Promise<void>;

export function OpenURL(arg1:string):Promise<void>;

export function RefreshPlugins():Promise<number|Array<string>>;

export function RemoveFund(arg1:string):Promise<void>;

export function RemoveFutures(arg1:string):Promise<void>;

export function RemoveHKStock(arg1:string):Promise<void>;

export function RemoveStock(arg1:string):Promise<void>;

export function RemoveUSStock(arg1:string):Promise<void>;

export function RenamePrompt(arg1:string,arg2:string,arg3:string):Promise<void>;

export function ResetStockAlert(arg1:number):Promise<void>;

export function SaveAIAnalysisResult(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function SaveAIChatMessage(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SaveConfig(arg1:models.Config):Promise<void>;

export function SearchFutures(arg1:string):Promise<Array<models.Futures>>;

export function SearchHKStock(arg1:string):Promise<Array<models.HKStock>>;

export function SearchUSStock(arg1:string):Promise<Array<models.USStock>>;

export function SellPosition(arg1:number,arg2:number,arg3:string):Promise<void>;

export function SendNotificationToAll(arg1:plugin.NotificationData):Promise<Array<Error>>;

export function SetActivePersona(arg1:string):Promise<void>;

export function SkipUpdateVersion(arg1:string):Promise<void>;

export function TestAIPlugin(arg1:string):Promise<string>;

export function TestAlertPush(arg1:string):Promise<void>;

export function TestDatasource(arg1:string,arg2:string):Promise<plugin.DatasourceResult>;

export function TestNotification(arg1:string):Promise<void>;

export function TogglePlugin(arg1:string,arg2:boolean):Promise<void>;

export function ToggleStockAlert(arg1:number,arg2:boolean):Promise<void>;

export function UpdatePlugin(arg1:Record<string, any>):Promise<void>;

export function UpdatePosition(arg1:models.Position):Promise<void>;

export function UpdatePrompt(arg1:string,arg2:string,arg3:string):Promise<prompt.PromptInfo>;

export function UpdateStockAlert(arg1:models.StockAlert):Promise<void>;
