// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AIAnalyzeByTypeStream(arg1, arg2, arg3) {
  return window['go']['main']['App']['AIAnalyzeByTypeStream'](arg1, arg2, arg3);
}

export function AIAnalyzeStock(arg1) {
  return window['go']['main']['App']['AIAnalyzeStock'](arg1);
}

export function AIAnalyzeStockStream(arg1) {
  return window['go']['main']['App']['AIAnalyzeStockStream'](arg1);
}

export function AIChat(arg1) {
  return window['go']['main']['App']['AIChat'](arg1);
}

export function AIChatStream(arg1) {
  return window['go']['main']['App']['AIChatStream'](arg1);
}

export function AIChatStreamWithPlugin(arg1, arg2) {
  return window['go']['main']['App']['AIChatStreamWithPlugin'](arg1, arg2);
}

export function AIChatWithPlugin(arg1, arg2) {
  return window['go']['main']['App']['AIChatWithPlugin'](arg1, arg2);
}

export function AIRecommend() {
  return window['go']['main']['App']['AIRecommend']();
}

export function AIRecommendStream() {
  return window['go']['main']['App']['AIRecommendStream']();
}

export function AISummarizeContentStream(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['AISummarizeContentStream'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function AddFund(arg1) {
  return window['go']['main']['App']['AddFund'](arg1);
}

export function AddFutures(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddFutures'](arg1, arg2, arg3);
}

export function AddHKStock(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddHKStock'](arg1, arg2, arg3);
}

export function AddPlugin(arg1) {
  return window['go']['main']['App']['AddPlugin'](arg1);
}

export function AddPosition(arg1) {
  return window['go']['main']['App']['AddPosition'](arg1);
}

export function AddStock(arg1) {
  return window['go']['main']['App']['AddStock'](arg1);
}

export function AddStockAlert(arg1) {
  return window['go']['main']['App']['AddStockAlert'](arg1);
}

export function AddUSStock(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['AddUSStock'](arg1, arg2, arg3, arg4);
}

export function CheckStockAlerts() {
  return window['go']['main']['App']['CheckStockAlerts']();
}

export function CheckUpdate() {
  return window['go']['main']['App']['CheckUpdate']();
}

export function CleanupAllCache() {
  return window['go']['main']['App']['CleanupAllCache']();
}

export function CleanupFinancialCache() {
  return window['go']['main']['App']['CleanupFinancialCache']();
}

export function CleanupNewsCache() {
  return window['go']['main']['App']['CleanupNewsCache']();
}

export function CleanupQuoteCache() {
  return window['go']['main']['App']['CleanupQuoteCache']();
}

export function CleanupReportCache() {
  return window['go']['main']['App']['CleanupReportCache']();
}

export function ClearCache() {
  return window['go']['main']['App']['ClearCache']();
}

export function ClearOldAIData() {
  return window['go']['main']['App']['ClearOldAIData']();
}

export function CreateAIPluginFromTemplate(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['CreateAIPluginFromTemplate'](arg1, arg2, arg3, arg4, arg5);
}

export function CreatePluginFromTemplate(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreatePluginFromTemplate'](arg1, arg2, arg3);
}

export function CreatePrompt(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreatePrompt'](arg1, arg2, arg3);
}

export function DeleteAIAnalysisResult(arg1) {
  return window['go']['main']['App']['DeleteAIAnalysisResult'](arg1);
}

export function DeleteAIChatSession(arg1) {
  return window['go']['main']['App']['DeleteAIChatSession'](arg1);
}

export function DeletePlugin(arg1) {
  return window['go']['main']['App']['DeletePlugin'](arg1);
}

export function DeletePosition(arg1) {
  return window['go']['main']['App']['DeletePosition'](arg1);
}

export function DeletePrompt(arg1, arg2) {
  return window['go']['main']['App']['DeletePrompt'](arg1, arg2);
}

export function DeleteStockAlert(arg1) {
  return window['go']['main']['App']['DeleteStockAlert'](arg1);
}

export function ExecuteIndicatorPrompt(arg1, arg2) {
  return window['go']['main']['App']['ExecuteIndicatorPrompt'](arg1, arg2);
}

export function ExecuteReviewPrompt(arg1) {
  return window['go']['main']['App']['ExecuteReviewPrompt'](arg1);
}

export function ExecuteScreenerPrompt(arg1) {
  return window['go']['main']['App']['ExecuteScreenerPrompt'](arg1);
}

export function ExecuteStrategyPrompt(arg1, arg2) {
  return window['go']['main']['App']['ExecuteStrategyPrompt'](arg1, arg2);
}

export function ExportAIAnalysisHistory(arg1) {
  return window['go']['main']['App']['ExportAIAnalysisHistory'](arg1);
}

export function ExportAIChatHistory(arg1, arg2) {
  return window['go']['main']['App']['ExportAIChatHistory'](arg1, arg2);
}

export function ExportPlugin(arg1) {
  return window['go']['main']['App']['ExportPlugin'](arg1);
}

export function ExportPrompt(arg1, arg2) {
  return window['go']['main']['App']['ExportPrompt'](arg1, arg2);
}

export function FetchQuoteFromAllPlugins(arg1) {
  return window['go']['main']['App']['FetchQuoteFromAllPlugins'](arg1);
}

export function FetchQuoteFromPlugin(arg1, arg2) {
  return window['go']['main']['App']['FetchQuoteFromPlugin'](arg1, arg2);
}

export function GetAIAnalysisHistory() {
  return window['go']['main']['App']['GetAIAnalysisHistory']();
}

export function GetAIChatHistory() {
  return window['go']['main']['App']['GetAIChatHistory']();
}

export function GetAIDataCleanupInfo() {
  return window['go']['main']['App']['GetAIDataCleanupInfo']();
}

export function GetAITemplates() {
  return window['go']['main']['App']['GetAITemplates']();
}

export function GetAShareSentiment() {
  return window['go']['main']['App']['GetAShareSentiment']();
}

export function GetActivePersona() {
  return window['go']['main']['App']['GetActivePersona']();
}

export function GetAllAlerts() {
  return window['go']['main']['App']['GetAllAlerts']();
}

export function GetCachedGlobalMarketData(arg1) {
  return window['go']['main']['App']['GetCachedGlobalMarketData'](arg1);
}

export function GetCachedMarketData() {
  return window['go']['main']['App']['GetCachedMarketData']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetDataCleanupInfo() {
  return window['go']['main']['App']['GetDataCleanupInfo']();
}

export function GetDatasourceTemplates() {
  return window['go']['main']['App']['GetDatasourceTemplates']();
}

export function GetEnabledAIPlugins() {
  return window['go']['main']['App']['GetEnabledAIPlugins']();
}

export function GetEnabledDatasourcePlugins() {
  return window['go']['main']['App']['GetEnabledDatasourcePlugins']();
}

export function GetForexRates() {
  return window['go']['main']['App']['GetForexRates']();
}

export function GetFundList() {
  return window['go']['main']['App']['GetFundList']();
}

export function GetFundPrice(arg1) {
  return window['go']['main']['App']['GetFundPrice'](arg1);
}

export function GetFuturesList() {
  return window['go']['main']['App']['GetFuturesList']();
}

export function GetFuturesPrice(arg1) {
  return window['go']['main']['App']['GetFuturesPrice'](arg1);
}

export function GetFuturesProducts() {
  return window['go']['main']['App']['GetFuturesProducts']();
}

export function GetGlobalIndices() {
  return window['go']['main']['App']['GetGlobalIndices']();
}

export function GetGlobalIndicesList() {
  return window['go']['main']['App']['GetGlobalIndicesList']();
}

export function GetGlobalMarketSentiment(arg1) {
  return window['go']['main']['App']['GetGlobalMarketSentiment'](arg1);
}

export function GetGlobalNews(arg1) {
  return window['go']['main']['App']['GetGlobalNews'](arg1);
}

export function GetHKStockList() {
  return window['go']['main']['App']['GetHKStockList']();
}

export function GetHKStockPrice(arg1) {
  return window['go']['main']['App']['GetHKStockPrice'](arg1);
}

export function GetHotTopics() {
  return window['go']['main']['App']['GetHotTopics']();
}

export function GetIndustryRank() {
  return window['go']['main']['App']['GetIndustryRank']();
}

export function GetKLineData(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetKLineData'](arg1, arg2, arg3);
}

export function GetLongTigerRank() {
  return window['go']['main']['App']['GetLongTigerRank']();
}

export function GetMainContracts() {
  return window['go']['main']['App']['GetMainContracts']();
}

export function GetMainForexPairs() {
  return window['go']['main']['App']['GetMainForexPairs']();
}

export function GetMarketIndex() {
  return window['go']['main']['App']['GetMarketIndex']();
}

export function GetMinuteData(arg1) {
  return window['go']['main']['App']['GetMinuteData'](arg1);
}

export function GetMoneyFlow() {
  return window['go']['main']['App']['GetMoneyFlow']();
}

export function GetNewsList() {
  return window['go']['main']['App']['GetNewsList']();
}

export function GetNotificationTemplates() {
  return window['go']['main']['App']['GetNotificationTemplates']();
}

export function GetPlugin(arg1) {
  return window['go']['main']['App']['GetPlugin'](arg1);
}

export function GetPlugins() {
  return window['go']['main']['App']['GetPlugins']();
}

export function GetPluginsByType(arg1) {
  return window['go']['main']['App']['GetPluginsByType'](arg1);
}

export function GetPluginsDir() {
  return window['go']['main']['App']['GetPluginsDir']();
}

export function GetPopularHKStocks() {
  return window['go']['main']['App']['GetPopularHKStocks']();
}

export function GetPopularUSStocks() {
  return window['go']['main']['App']['GetPopularUSStocks']();
}

export function GetPositionByStock(arg1) {
  return window['go']['main']['App']['GetPositionByStock'](arg1);
}

export function GetPositionHistory() {
  return window['go']['main']['App']['GetPositionHistory']();
}

export function GetPositions() {
  return window['go']['main']['App']['GetPositions']();
}

export function GetPrompt(arg1, arg2) {
  return window['go']['main']['App']['GetPrompt'](arg1, arg2);
}

export function GetPromptTypes() {
  return window['go']['main']['App']['GetPromptTypes']();
}

export function GetPromptsDir() {
  return window['go']['main']['App']['GetPromptsDir']();
}

export function GetResearchReports(arg1) {
  return window['go']['main']['App']['GetResearchReports'](arg1);
}

export function GetStockAlerts(arg1) {
  return window['go']['main']['App']['GetStockAlerts'](arg1);
}

export function GetStockList() {
  return window['go']['main']['App']['GetStockList']();
}

export function GetStockNotices(arg1) {
  return window['go']['main']['App']['GetStockNotices'](arg1);
}

export function GetStockPrice(arg1) {
  return window['go']['main']['App']['GetStockPrice'](arg1);
}

export function GetTradingTimeInfo() {
  return window['go']['main']['App']['GetTradingTimeInfo']();
}

export function GetUSStockList() {
  return window['go']['main']['App']['GetUSStockList']();
}

export function GetUSStockPrice(arg1) {
  return window['go']['main']['App']['GetUSStockPrice'](arg1);
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function HasEnabledAIPlugins() {
  return window['go']['main']['App']['HasEnabledAIPlugins']();
}

export function HasEnabledDatasourcePlugins() {
  return window['go']['main']['App']['HasEnabledDatasourcePlugins']();
}

export function HasEnabledNotificationPlugins() {
  return window['go']['main']['App']['HasEnabledNotificationPlugins']();
}

export function ImportPlugin(arg1) {
  return window['go']['main']['App']['ImportPlugin'](arg1);
}

export function ImportPrompt(arg1, arg2, arg3) {
  return window['go']['main']['App']['ImportPrompt'](arg1, arg2, arg3);
}

export function IsFirstLoad() {
  return window['go']['main']['App']['IsFirstLoad']();
}

export function ListAllPrompts() {
  return window['go']['main']['App']['ListAllPrompts']();
}

export function ListPrompts(arg1) {
  return window['go']['main']['App']['ListPrompts'](arg1);
}

export function MarkFirstLoadComplete() {
  return window['go']['main']['App']['MarkFirstLoadComplete']();
}

export function OpenPluginsDir() {
  return window['go']['main']['App']['OpenPluginsDir']();
}

export function OpenPromptsDir() {
  return window['go']['main']['App']['OpenPromptsDir']();
}

export function OpenURL(arg1) {
  return window['go']['main']['App']['OpenURL'](arg1);
}

export function RefreshPlugins() {
  return window['go']['main']['App']['RefreshPlugins']();
}

export function RemoveFund(arg1) {
  return window['go']['main']['App']['RemoveFund'](arg1);
}

export function RemoveFutures(arg1) {
  return window['go']['main']['App']['RemoveFutures'](arg1);
}

export function RemoveHKStock(arg1) {
  return window['go']['main']['App']['RemoveHKStock'](arg1);
}

export function RemoveStock(arg1) {
  return window['go']['main']['App']['RemoveStock'](arg1);
}

export function RemoveUSStock(arg1) {
  return window['go']['main']['App']['RemoveUSStock'](arg1);
}

export function RenamePrompt(arg1, arg2, arg3) {
  return window['go']['main']['App']['RenamePrompt'](arg1, arg2, arg3);
}

export function ResetStockAlert(arg1) {
  return window['go']['main']['App']['ResetStockAlert'](arg1);
}

export function SaveAIAnalysisResult(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SaveAIAnalysisResult'](arg1, arg2, arg3, arg4);
}

export function SaveAIChatMessage(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveAIChatMessage'](arg1, arg2, arg3);
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SearchFutures(arg1) {
  return window['go']['main']['App']['SearchFutures'](arg1);
}

export function SearchHKStock(arg1) {
  return window['go']['main']['App']['SearchHKStock'](arg1);
}

export function SearchUSStock(arg1) {
  return window['go']['main']['App']['SearchUSStock'](arg1);
}

export function SellPosition(arg1, arg2, arg3) {
  return window['go']['main']['App']['SellPosition'](arg1, arg2, arg3);
}

export function SendNotificationToAll(arg1) {
  return window['go']['main']['App']['SendNotificationToAll'](arg1);
}

export function SetActivePersona(arg1) {
  return window['go']['main']['App']['SetActivePersona'](arg1);
}

export function TestAIPlugin(arg1) {
  return window['go']['main']['App']['TestAIPlugin'](arg1);
}

export function TestDatasource(arg1, arg2) {
  return window['go']['main']['App']['TestDatasource'](arg1, arg2);
}

export function TestNotification(arg1) {
  return window['go']['main']['App']['TestNotification'](arg1);
}

export function TogglePlugin(arg1, arg2) {
  return window['go']['main']['App']['TogglePlugin'](arg1, arg2);
}

export function ToggleStockAlert(arg1, arg2) {
  return window['go']['main']['App']['ToggleStockAlert'](arg1, arg2);
}

export function UpdatePlugin(arg1) {
  return window['go']['main']['App']['UpdatePlugin'](arg1);
}

export function UpdatePosition(arg1) {
  return window['go']['main']['App']['UpdatePosition'](arg1);
}

export function UpdatePrompt(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdatePrompt'](arg1, arg2, arg3);
}

export function UpdateStockAlert(arg1) {
  return window['go']['main']['App']['UpdateStockAlert'](arg1);
}
